# This file can be stored in your repository under .github/workflows/deploy.yml, for example.
name: Deploy
on:
  push:
    branches: [ "mine" ]
  workflow_dispatch:
env:
    play_while_download_oauth: ${{ secrets.play_while_download_oauth }}
jobs:


  deploy:


    # Important: must be run from Linux.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'jetbrains'


      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Build with Gradle Wrapper
        run: ./gradlew jar
      - name: Run Conveyor
        uses: hydraulic-software/conveyor/actions/build@v20.0
        env:
          OAUTH_TOKEN: ${{ secrets.PLAY_WHILE_DOWNLOAD_OAUTH }}
          PWD: ${{ secrets.SOURCEFORGE_PWD }}
        with:
          command:    make copied-site
          signing_key: ${{ secrets.SIGN_KEY }}
          agree_to_license: 1
          extra_flags: --show-log=error
          cache_key: 'conveyor'
          cache_path: '.conveyor'